### ISSUE TITLE
Shortlist and Finalize the template for Unblox Website

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#1]
Check the following to shortlist templates - 

1. https://elements.envato.com/
2. https://www.templatemonster.com/
3. https://themeforest.net/ 

Note - The template should be shortlisted keeping in mind -  

1. The color (orange) of Unblox logo
2. Podcast integration
3. Blogs
4. Team Section

https://unblox.com/

- [x] Shortlist templates 
- [x] Send shortlisted templates for review 
- [x] Finalize the best one

**Comment by manujuniris** [comment]
1. https://www.templatemonster.com/website-templates/alternat-ico-cryptocurrency-bitcoin-responsive-website-template-189318.html
2. https://www.templatemonster.com/website-templates/cryptobit-cryptocurrency-blockchain-amp-crypto-ico-nft-html5-template-247427.html
3. https://www.templatemonster.com/landing-page-template/victor-modern-unique-3d-landing-page-template-198892.html
4. https://www.templatemonster.com/website-templates/cryptocurrency-ico-amp-bitcoin-html5-website-template-217796.html
5. https://www.templatemonster.com/website-templates/cryptorius-ico-bitcoin-and-cryptocurrency-html-website-template-239263.html
6. https://www.templatemonster.com/website-templates/cryptobit-crypto-amp-blockchain-html5-template-260260.html
7. https://themeforest.net/item/kryptova-bitcoin-cryptocurrency-ico-landing-page-template/21837838
8. https://themeforest.net/item/cryptox-ico-cryptocurrency-template/23292231
9. https://themeforest.net/item/crizal-ico-and-cryptocurrency-html-template/25257053
10. https://themeforest.net/item/crypto-ico-cryptocurrency-website-landing-page-html-dashboard-template/21968965
11. https://themeforest.net/item/trypto-ico-and-cryptocurrency-landing-page-html-template/22311854
12. https://themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/22832072

**Comment by nilesh-uniris** [comment]
It is a great selection of templates. Following are the four we shortlisted:

1. https://www.templatemonster.com/landing-page-template/victor-modern-unique-3d-landing-page-template-198892.html
2. https://www.templatemonster.com/website-templates/cryptobit-crypto-amp-blockchain-html5-template-260260.html
3. https://themeforest.net/item/crypto-ico-cryptocurrency-website-landing-page-html-dashboard-template/21968965
4. https://themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/22832072

4 and 2 would be amongst the top choices. We will need to discuss the merit/demerit of choosing one of these for our needs.

**Comment by manujuniris** [comment]
> It is a great selection of templates. Following are the four we shortlisted:
> 
> 1. https://www.templatemonster.com/landing-page-template/victor-modern-unique-3d-landing-page-template-198892.html
> 2. https://www.templatemonster.com/website-templates/cryptobit-crypto-amp-blockchain-html5-template-260260.html
> 3. https://themeforest.net/item/crypto-ico-cryptocurrency-website-landing-page-html-dashboard-template/21968965
> 4. https://themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/22832072
> 
> 4 and 2 would be amongst the top choices. We will need to discuss the merit/demerit of choosing one of these for our needs.

Hi Nilesh,

1.https://themeforest.net/item/crypto-ico-cryptocurrency-website-landing-page-html-dashboard-template/21968965
2.https://themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/22832072

The above two can be the top 2 choices as they look more attractive on mobile screens and most users will access the website from their phones.

While the following two look suitable for desktop screens but not for mobile screens - 

1.https://www.templatemonster.com/landing-page-template/victor-modern-unique-3d-landing-page-template-198892.html
2.https://www.templatemonster.com/website-templates/cryptobit-crypto-amp-blockchain-html5-template-260260.html

**Comment by manujuniris** [comment]
Final Template - https://themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/22832072

**Comment by manujuniris** [comment]
Hi Nilesh,


1.https://themeforest.net/item/crypto-ico-cryptocurrency-website-landing-page-html-dashboard-template/21968965

2.https://themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/22832072


The above two can be the top 2 choices as they look more attractive on mobile screens and most users will access the website from their phones.


While the following two look suitable for desktop screens but not for mobile screens -


1.https://www.templatemonster.com/landing-page-template/victor-modern-unique-3d-landing-page-template-198892.html

2.https://www.templatemonster.com/website-templates/cryptobit-crypto-amp-blockchain-html5-template-260260.html


________________________________
