### ISSUE TITLE
Optimize press section

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#10]
- [x] add wef interview article 
https://medium.datadriveninvestor.com/accelerating-towards-a-more-inclusive-society-with-ai-and-blockchain-b72135f1d364

**Comment by manujuniris** [comment]
Hi @nilesh-uniris

I have added WEF interview article, please review it via following link - 

https://unbloxtech.github.io/pre-production/#press

**Comment by samiran-ghosh** [comment]
This works. Do you think we should add icons for Forbes, WEF, TEDx and Cointelegraph here instead of writing the names?

**Comment by manujuniris** [comment]
Yes, it is a good proposal. Forbes, TEDx & Cointelegraph logos will be easy to accomodate, for WEF it will be challenge but I will try and share the link here again.

**Comment by manujuniris** [comment]
> This works. Do you think we should add icons for Forbes, WEF, TEDx and Cointelegraph here instead of writing the names?
Hi @samiran-ghosh & @nilesh-uniris 

I have added icons for Forbes,WEF,TEDx & Cointelegraph, please check the following two proposals - 

1. https://unbloxtech.github.io/pre-production/press-1.html#press
2. https://unbloxtech.github.io/pre-production/press-2.html#press

Text instead of logos - https://unbloxtech.github.io/pre-production/#press

**Comment by samiran-ghosh** [comment]
I like these. Very eye-catching

**Comment by manujuniris** [comment]
> I like these. Very eye-catching

Can we finalize any one ?

**Comment by samiran-ghosh** [comment]
I am a little confused between the B/W and colour. I think the colour looks nice unless we decide that we are going to be a two colour website by choice

**Comment by manujuniris** [comment]
> I am a little confused between the B/W and colour. I think the colour looks nice unless we decide that we are going to be a two colour website by choice

Ok this can be a point of discussion for our next meeting.

**Comment by nilesh-uniris** [comment]
I also like the colored ones so let's go with option 2.
