### ISSUE TITLE
Optimize 'About' section

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#11]
Sprint 15 -

- [x] design this section to show strong association with archethic
- [x] get appropriate content for this section 
- [x] display numbers for example 12 patents, 97.5 (consensus security), < 5 sec (validation time) etc 
https://html.crumina.net/woox-crypto/026_counters_and_timers.html
https://html.crumina.net/woox-crypto/024_progress_bars.html
 
Sprint 16 -

- [x] optimize metrics section
- [x] Fix size of comparison table
- [x] Check with victor the unit of "fees" in comparison table
- [x] Add a disclaimer for comparison table
- [x] Change content of "About" section, after consulting Nilesh & Samiran

**Comment by manujuniris** [comment]
Hi @nilesh-uniris & @samiran-ghosh

The about section on website has been optimized please review the following link - 
https://unbloxtech.github.io/pre-production/#about

**Comment by samiran-ghosh** [comment]
I like the key elements that you mentioned and the design. Is there a table that compares our numbers with others? A claim without context is not impactful.

Also, we should write something about how we are ideal for anything and everything that needs scale. Like elections, email, payments, e-commerce...

**Comment by samiran-ghosh** [comment]
The unblox everywhere needs to be in small case

**Comment by manujuniris** [comment]
> I like the key elements that you mentioned and the design. Is there a table that compares our numbers with others? A claim without context is not impactful.
> 
> Also, we should write something about how we are ideal for anything and everything that needs scale. Like elections, email, payments, e-commerce...

Hi @samiran-ghosh 

We can surely create a table for comparing our numbers with others, following are the designs that we can use - 
https://unbloxtech.github.io/pre-production/018_tables.html

I like your proposal about mentioning something like decentralized email, web, payments etc.

I will communicate about this to Vishnupriya and take it forward.

**Comment by manujuniris** [comment]
> The unblox everywhere needs to be in small case

Fixed it in recent commit

**Comment by vpmishra01** [comment]
> > I like the key elements that you mentioned and the design. Is there a table that compares our numbers with others? A claim without context is not impactful.
> > Also, we should write something about how we are ideal for anything and everything that needs scale. Like elections, email, payments, e-commerce...
> 
> Hi @samiran-ghosh
> 
> We can surely create a table for comparing our numbers with others, following are the designs that we can use - https://unbloxtech.github.io/pre-production/018_tables.html
> 
> I like your proposal about mentioning something like decentralized email, web, payments etc.
> 
> I will communicate about this to Vishnupriya and take it forward.

We will replicate the same table as Archethic has unless we add new competition

**Comment by manujuniris** [comment]
> I like the key elements that you mentioned and the design. Is there a table that compares our numbers with others? A claim without context is not impactful.
> 
> Also, we should write something about how we are ideal for anything and everything that needs scale. Like elections, email, payments, e-commerce...

Table published - 
https://unbloxtech.github.io/pre-production/#about

**Comment by vpmishra01** [comment]
> 

We will just add 1 line about this as a new brand seeking out investors should not present multiple usecases. When we transitioned from Uniris to Archethic, we had a ready audience but for unblox we need to do that from scratch so lets go with 1 single proposition:  fastest,most secure and most energy efficient blockchain to buidl.

**Comment by manujuniris** [comment]
@nilesh-uniris & @samiran-ghosh will decide the exact content for about section on website
