### ISSUE TITLE
Design and propose the structure of website 

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#2]
- [x] Buy a template 
- [x] Make a quick finalization of different sections required on website
- [x] Design and implement a basic structure of website

1. Landing Section with punch line
2. About us / What is Unblox ?
4. Podcast 
5. Blogs 
6. Team 
7. Contact us 
8. Social Media Icons 

- [x] Get it reviewed

**Comment by unbloxtech** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/unbloxtech/unblox-website/2?planning-poker) with Zenhub @internet-zero

**Comment by unbloxtech** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/unbloxtech/unblox-website/2?planning-poker) with Zenhub @manujuniris

**Comment by unbloxtech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/unbloxtech/unblox-website/2?planning-poker) with Zenhub @internet-zero @manujuniris
