### ISSUE TITLE
Teams Section 

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#3]
- [x] Get the photographs of Team Members 
- [x] Implement a Team's Section on Main Page - 
1. https://preview.themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/full_screen_preview/22832072?_ga=2.111301894.383572983.1661408921-17689950.1630871609
2. https://preview.themeforest.net/item/woox-crypto-icocoins-and-cryptocurrency-html-website-template/full_screen_preview/22832072?_ga=2.111301894.383572983.1661408921-17689950.1630871609
- [x] Navigate profiles to the LinkedIn profile of every team member

**Comment by unbloxtech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/unbloxtech/unblox-website/3?planning-poker) with Zenhub @internet-zero @manujuniris
