### ISSUE TITLE
Optimize footer

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#6]
- [x] change social media icons in footer with those used on archethic website in community section
- [x] add a brief description about unblox

**Comment by manujuniris** [comment]
Hi @nilesh-uniris 

I have changed social media icons & description in footer - 

![Screenshot 2022-09-09 175609](https://user-images.githubusercontent.com/90322956/189350361-eb8171a0-5cb5-4e59-8a91-5fe8d25474fe.jpg)

Please review the following link - 
https://unbloxtech.github.io/pre-production/index.html#contact

**Comment by samiran-ghosh** [comment]
This looks neat. Maybe if it were a little sharper image, it would be nicer. Do you think we should use colour outlines for the icons? Like the blue of Twitter?

**Comment by manujuniris** [comment]
It is possible to resize the image either small or large which could make it sharper. I tried using coloured icons but it didn't go well with the overall theme.

Check the image below - 

![Screenshot 2022-09-09 174655](https://user-images.githubusercontent.com/90322956/190098391-98842549-84ce-4646-a08e-b675e3fa6f9a.jpg)

**Comment by manujuniris** [comment]
> This looks neat. Maybe if it were a little sharper image, it would be nicer. Do you think we should use colour outlines for the icons? Like the blue of Twitter?

Please check the link below for coloured icons - 
https://unbloxtech.github.io/pre-production/press-1.html#contact
