### ISSUE TITLE
Optimize landing section 

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#7]
Sprint 15 -

The landing section on website is the first impression and it has to be engaging such that users should spend some more time on it 
- [x] implement particles js on landing section and check it look & feel 
- [x] explore more options like video background, 3d graphics, gif etc
- [x] optimize text blockchain, identity & crypto-biometrics
- [ ] ~navigate "Join our community" to telegram channel~
- [x] "Listen podcasts" is not the correct call to action, validate and change it
- [x] optimize the landing section for mobile screen
- [x] display association with archethic on landing section

Sprint 16 -
 - [x] Edit videos according to the theme of website
 - [x] Try different font colors for titles
 - [x] Change color of navbar elements according to video in background
 - [x] Change color of divider 
 - [x] try to move "Powered by Archethic" to bottom, since it's constant in three slides
 - [x] Try different shape of arrows for slider 
 - [x] Add a sub-title for each title
 - [x] Optimize mobile version of landing section

**Comment by manujuniris** [comment]
Hi @nilesh-uniris & @samiran-ghosh

I have implemented particles-js on landing section, please review it through the following link - 
https://unbloxtech.github.io/pre-production/press-1.html

**Comment by nilesh-uniris** [comment]
It is looking quite interesting.

**Comment by manujuniris** [comment]
Hello @samiran-ghosh and @nilesh-uniris 

Please review the following link for landing section - 
https://unbloxtech.github.io/pre-production/

Video editing/change of video, change of fonts color and change of slider button can be under scope of improvement.
