### ISSUE TITLE
Optimize team section

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/unblox-website#8]
The problem with team section is that it shows only 3 team members (desktop screen) and to view fourth member users have to click
- [x] display seb profile first
- [x] explore more designs to accomodate four profiles in single view 
- [x] add designation for all members

**Comment by manujuniris** [comment]
Hi @nilesh-uniris 

Please review the 3 proposed designs to display 4 profiles in single view - 
https://unbloxtech.github.io/pre-production/team.html

**Comment by samiran-ghosh** [comment]
Neat. The only issue with this is what happens when we have more people. Is the carousel approach better with focusing on 3 people at a time?

**Comment by manujuniris** [comment]
https://unbloxtech.github.io/pre-production/team.html 

Carousel is also possible in the first 2 designs.

**Comment by manujuniris** [comment]
> Neat. The only issue with this is what happens when we have more people. Is the carousel approach better with focusing on 3 people at a time?

@nilesh-uniris also proposed to go with the existing design for team section https://unbloxtech.github.io/pre-production/index.html#team
Though we will change it as we add more members.
